name: build
on:
  push:
    branches-ignore:
      - master

env:
  E1: test

jobs:
  test_env_1:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - name: test1
      run: |
        echo ${E1}
        echo '::set-env name=E1::test2'
  test_env_2:
    needs: test_env_1
    name: Test
    runs-on: ubuntu-latest
    steps:
    - name: test2
      run: |
        echo ${E1}