name: build
on:
  push:
    branches-ignore:
      - master

jobs:
  test_env_1:
    name: Test1
    runs-on: ubuntu-latest
    steps:
    - name: test1
      run: |
        echo "::set-env name=PR::OK"
    - name: test2
      run: |
        echo ${{ env.PR }}
    - name: test3
      if: env.PR == 'OK'
      run: |
        echo "OK!"