name: build
on:
  push:
    branches-ignore:
      - master

# jobs:
#   test_env_1:
#     name: Test
#     runs-on: ubuntu-latest
#     outputs:
#       output1: ${{ steps.steps.j1.outputs.pr }}
#     steps:
#     - name: test1
#       id: j1
#       run: |
#         echo "::set-output name=pr::OK"
#   test_env_2:
#     needs: test_env_1
#     name: Test
#     runs-on: ubuntu-latest
#     steps:
#     - name: test2
#       run: |
#         echo ${{needs.test_env_1.outputs.output1}}
#     - name: check if
#       if: needs.test_env_1.outputs.output1 != 'OK'
#       run: echo skip?
jobs:
  job1:
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      output1: ${{ steps.step1.outputs.test }}
      output2: ${{ steps.step2.outputs.test }}
    steps:
    - id: step1
      run: echo "::set-output name=test::hello"
    - id: step2
      run: echo "::set-output name=test::world"
  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
    - run: echo ${{needs.job1.outputs.output1}} ${{needs.job1.outputs.output2}}