name: build
on:
  push:
    branches-ignore:
      - master

env:
  SKIP: false

jobs:
  test_env_1:
    name: Test1
    runs-on: ubuntu-latest
    steps:
    - name: test1
      run: |
        pr=$(echo OK)
        echo ${pr}
        echo "::set-env name=PR::${pr}"
    - name: test2
      run: |
        echo ${{ env.SKIP }}
        echo ${{ env.PR }}
    - name: test3
      if: env.SKIP == 'false'
      run: |
        echo "OK!"